<a href="https://colab.research.google.com/github/junggangwo/pdm07/blob/main/numpy/numpy_0_why_use_it.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy  
## What is numpy?  
* python module to do math!  
    - random number
    - array -> ndarray
    - math operations
    - ...

#### Why do data coders use & enjoy it?

In [ ]:
a=range(10)
a

range(0, 10)

In [ ]:
la=list(a)
la, type(la)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], list)

> 그러면 리스트 각 요소를 2배, 또는 5배로 변경하는 방법은?

In [ ]:
2*la               # 리스트 복제 -> 리스트 확장

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 우리가 원하는 결과가 아니다.

- #### 리스트 comprehension 구조




In [ ]:
[5 * i for i in la]  

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

In [ ]:
[2 * i for i in la]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
import numpy as np  # 행렬 계산 함수 모듈, as np ->  별명 정하기

In [ ]:
la, type(la)                 # 데이터 구조 => 리스트

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [ ]:
larr = np.array(la) # array 함수 사용 (리스트 -> numpy배열)
larr                # broadcasted multiplication

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
larr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# Try below!
la = np.array(a) # range: a 
la               # array 함수 사용 (range -> numpy배열)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy가 데이터 코딩, 특히 딥러닝에 이용되는 예제

> http://life21c.inje.ac.kr:8501/


- numpy array vs. list

    *  머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지 데이터를 행렬(matrix)로 변환하는 것이 중요하다.
    *  행렬을 나타내기 위해서는 list를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에 **행렬 연산을 위해서는 numpy 사용이 필수적**이다.

---